export default {
  any: { type: 'any', isRequired: { type: 'any', required: true } },
  array: { type: 'array', isRequired: { type: 'array', required: true } },
  bool: { type: 'bool', isRequired: { type: 'bool', required: true } },
  element: { type: 'element', isRequired: { type: 'element', required: true } },
  func: { type: 'func', isRequired: { type: 'func', required: true } },
  node: { type: 'node', isRequired: { type: 'node', required: true } },
  number: { type: 'number', isRequired: { type: 'number', required: true } },
  object: { type: 'object', isRequired: { type: 'object', required: true } },
  string: { type: 'string', isRequired: { type: 'string', required: true } },
  symbol: { type: 'symbol', isRequired: { type: 'symbol', required: true } },
  arrayOf: args => ({ type: 'arrayOf', args, isRequired: { type: 'arrayOf', args, required: true } }),
  instanceOf: args => ({ type: 'instanceOf', args, isRequired: { type: 'instanceOf', args, required: true } }),
  objectOf: args => ({ type: 'objectOf', args, isRequired: { type: 'objectOf', args, required: true } }),
  oneOfType: args => ({ type: 'oneOfType', args, isRequired: { type: 'oneOfType', args, required: true } }),
  oneOf: args => ({ type: 'oneOf', args, isRequired: { type: 'oneOf', args, required: true } }),
  shape: args => ({ type: 'shape', args, isRequired: { type: 'shape', args, required: true } }),
};
